dist: releases

builds:
  - id: default
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -X "main.Version=v{{ .Version }}"
      - -X "main.Commit={{ .FullCommit }}"

archives:
  - id: default
    format: binary
    name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    replacements:
      darwin: macOS

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge pull request"

brews:
  - description: "tmctl"
    homepage: "https://github.com/triggermesh/tmctl"
    license: "Apache 2.0"
    tap:
      owner: triggermesh
      name: homebrew-cli
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
